### PR TITLE
Spinner

### PR DESCRIPTION
**Pull request by Emmanuel-Melon**

### CODE REVIEW

**Comment by Emmanuel-Melon** [comment]
@Hiiiij the ball is in your court

**Review by Ladu-Lumori — APPROVED** [review]

**Review by Ladu-Lumori — DISMISSED** [review]
Why didnt you use the chakra ui image component (Image) instead of the img component to create the spinner component?

**Comment by Emmanuel-Melon** [comment]
> Why didnt you use the chakra ui image component (Image) instead of the img component to create the spinner component?

It's recommended to use the Next.js Image component due to the opimtizations Next provides.

**Review by Hiiiij — APPROVED** [review]
LGTM :)

**Pull request merged**
